(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "browse-kill-ring")
(depends-on "cl")
(depends-on "cyberpunk-theme")
(depends-on "flymake-ruby")
(depends-on "grizzl")
(depends-on "ido-vertical-mode")
(depends-on "inf-ruby")
(depends-on "magit")
(depends-on "maxframe")
(depends-on "melpa")
(depends-on "monokai-theme")
(depends-on "multi-term")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "projectile")
(depends-on "rcirc")
(depends-on "rings")
(depends-on "robe")
(depends-on "ruby-compilation")
(depends-on "rvm")
(depends-on "smex")
(depends-on "smooth-scrolling")
(depends-on "textmate")
(depends-on "todochiku")
(depends-on "tree-mode")
(depends-on "undo-tree")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "markdown-mode")